# Generated by Django 2.1.11 on 2019-12-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191206_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_page', models.CharField(max_length=50)),
                ('res', models.CharField(max_length=99999)),
                ('Statut_res', models.CharField(max_length=10)),
            ],
        ),
    ]
